---
title: "R Notebook"
output: html_notebook
---

```{r}
finaldata$loggdp <- log(finaldata$gdp1000)
finaldata$pctpopdens <- finaldata$popdens / 100
names(finaldata)[15] <- "armcon"
```

```{r}
library(tidyverse)
midata <- finaldata |>
  mutate(ISOnum = as.numeric(as.factor(finaldata$ISO))) |>
  select(-country_name, -ISO, -gdp1000, -popdens, -region, -OECD2023)
```
```{r}
library(mice)
mice0  <- mice(midata, seed = 100, m = 5, maxit = 0, print = F)
```
```{r}
meth <- mice0$method
meth[c("urban", "male_edu", "temp", "rainfall1000", "matmor", "infmor", "neomor", "un5mor", "loggdp", "pctpopdens")] <- "2l.lmer"

pred <- mice0$predictorMatrix
pred[c("urban", "male_edu", "temp", "rainfall1000", "matmor", "infmor", "neomor", "un5mor", "loggdp", "pctpopdens"), "ISOnum"] <- -2
```

```{r}
mice.multi.out  <- mice(midata, seed = 100, m = 10, maxit = 20,
                        method = meth,
                        predictorMatrix = pred)
```

```{r}
library(here)
save(mice.multi.out, file = here("data", "mi_data.Rdata"))
```

```{r}
plot(mice.multi.out)
```
```{r}
# multiple imputation regression results
fit.matmormod <- with(mice.multi.out,
                      lm(matmor ~ -1 + armcon + loggdp + OECD + 
                                        pctpopdens + urban + agedep + male_edu + 
                                        temp + rainfall1000 + earthquake + 
                                        drought + as.factor(ISOnum) + as.factor(year)))
fit.un5mormod <- with(mice.multi.out,
                      lm(un5mor ~ -1 + armcon + loggdp + OECD + 
                                        pctpopdens + urban + agedep + male_edu + 
                                        temp + rainfall1000 + earthquake + 
                                        drought + as.factor(ISOnum) + as.factor(year)))
fit.infmormod <- with(mice.multi.out,
                      lm(infmor ~ -1 + armcon + loggdp + OECD + 
                                        pctpopdens + urban + agedep + male_edu + 
                                        temp + rainfall1000 + earthquake + 
                                        drought + as.factor(ISOnum) + as.factor(year)))
fit.neomormod <- with(mice.multi.out,
                      lm(neomor ~ -1 + armcon + loggdp + OECD + 
                                        pctpopdens + urban + agedep + male_edu + 
                                        temp + rainfall1000 + earthquake + 
                                        drought + as.factor(ISOnum) + as.factor(year)))

mi.matmormod <- pool(fit.matmormod)
mi.un5mormod <- pool(fit.un5mormod)
mi.infmormod <- pool(fit.infmormod)
mi.neomormod <- pool(fit.neomormod)
```


```{r}
# complete case regression results
preds <- as.formula(" ~ -1 + armcon + loggdp + OECD + pctpopdens + urban + 
                  agedep + male_edu + temp + rainfall1000 + earthquake + drought + 
                  as.factor(ISO) + as.factor(year)")

cc.matmormod <- lm(update.formula(preds, matmor ~ .), data = finaldata)
cc.un5mormod <- lm(update.formula(preds, un5mor ~ .), data = finaldata)
cc.infmormod <- lm(update.formula(preds, infmor ~ .), data = finaldata)
cc.neomormod <- lm(update.formula(preds, neomor ~ .), data = finaldata)
```


```{r}
# Create tables
tosave <- list(cc.matmormod, mi.matmormod, cc.un5mormod, mi.un5mormod, cc.infmormod, 
               mi.infmormod, cc.neomormod, mi.neomormod)

keepvars <- list("armcon" = "Armed conflict - binary",
                 "loggdp" = "log(GDP)",
                 "OECD" = "OECD",
                 "pctpopdens" = "Population density",
                 "urban" = "Urban residence",
                 "agedep" = "Age dependency ratio",
                 "male_edu" = "Male education",
                 "temp" = "Average temperature",
                 "rainfall1000" = "Average rainfall",
                 "earthquake" = "Earthquake",
                 "drought" = "Drought")

screenreg(tosave, ci.force = TRUE, custom.coef.map = keepvars, 
          custom.model.names = c("Mat CC", "Mat MI", "Un5 CC", "Un5 MI", "Inf CC", 
                                 "Inf MI", "Neo CC", "Neo MI"))

save(tosave, file = here("data", "mi_output.Rdata"))
```
