---
title: "R Notebook"
output: html_notebook
---

```{r}
library(here)
library(tidyverse)
rdf <- read.csv(here("original","disaster.csv"),header = T)
```


a. Use the filter() function to subset the data set to only include years 2000–2019
and the disaster types “Earthquake” and “Drought”

```{r}
ddf <- rdf[rdf$Year >= 2000 & rdf$Year <= 2019 & (rdf$Disaster.Type=="Earthquake"|rdf$Disaster.Type=="Drought"),]
```

b. Subset the data set to only include the following variables: Year, ISO,
Disaster.type.

```{r}
sdf <- ddf[,c("Year","ISO","Disaster.Type")]
names(sdf)[1]<-"year"
```

c. Create a dummy variable drought and another dummy variable earthquake

```{r}
disaster_grouped <- dplyr::group_by(sdf, year, ISO)
disaster_mutated <- dplyr::mutate(disaster_grouped, 
                                  drought0 = ifelse(Disaster.Type == "Drought", 1, 0),
                                  earthquake0 = ifelse(Disaster.Type == "Earthquake", 1, 0))

disasters_summarized <- dplyr::summarize(disaster_mutated, 
                                         drought = max(drought0),
                                         earthquake = max(earthquake0))

disasters <- dplyr::ungroup(disasters_summarized)
```

```{r}
write_csv(disasters,here("data","disastor.csv"))
```

